# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Apollo iOS Guide
subtitle: Using Apollo with iOS
versions:
  - '1'
sidebar_categories:
  null:
    - index
    - installation
    - api-reference
  Usage:
  - downloading-schema
  - initialization
  - fetching-queries
  - fragments
  - watching-queries
  - mutations
github_repo: apollographql/apollo-ios
content_root: source

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.apollographql.com/docs/ios/
root: /docs/ios/

public_dir: public/docs/ios
